# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f67b7f25000e35a1f84600100d6722ae36247aacb51b2c19e78f9fd6e4007019197295ddda81daea23530726f64066f58a1b80146e94ddc0364e71c4b00605b

test:
  secret_key_base: 5c8a151517ec50741b108ee5b3d4c12cd7ee503bfdc4c9b7c65a32243a8227bbfa58559e9fc9464a050b470a7e388019f6e3b381060b75ddfb56356dc1c041b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
